config/routes.rb
Rails.application.routes.draw do
  root "boards#index"
  
  resource :users, controller: 'registrations',only: [:create, :edit, :update] do 
     get '/sign_up', action: 'new' 
  end
# post '/users', to: 'registrations#create'
# get "/users/edit", to: "registrations#edit", as: 'edit_registration'
# put "/users/edit", to: "registrations#update", as: 'update _registration'

  resource :users, controller: 'sessions',only: [] do 
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create' 
    delete '/sign_out', action: 'destroy'
  end

  # get '/users/sign_in', to: 'sessions#new', as: 'session'
  # post '/login', to: 'sessions#create', as: 'login'
  # delete '/users/sign_out', to: 'sessions#destroy', as: 'logout'

  resources :boards do
    resources :posts, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true,length: { minimum: 4 }
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true

  def owned_by?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true,
                    uniqueness: true, 
                    format: { with: /[\w]+@([\w-]+\.)+[\w-]{2,4}/ } 
  validates :password, presence: true, confirmation: true, length: {minimum: 4}
  validates :nickname, presence: true
  
  before_create :encrypt_password

  has_many :posts

  def self.login(u)
    pw = Digest::SHA1.hexdigest("a#{u[:password]}z")
    User.find_by(email: u[:email], password: pw)
  end


  private
  def encrypt_password
    self.password = Digest::SHA1.hexdigest("a#{self.password}z")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
    def session_required
      redirect_to sign_in_users_path, notice: '請先登入' if not current_user
    end

    def record_not_found
      render file: '/public/404.html' ,layout: false,status: 404
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :find_board, only: [:show, :edit , :update , :destroy]

  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    # clear_params = params.require(:board).permit(:title)
    @board = Board.new(clear_params)
    if @board.save
      redirect_to '/',notice: "新增成功"
    else
      render :new
    end
  end

  def show
    # @board = Board.find(params[:id])
    @posts = @board.posts.order(id: :desc)
  end

  def edit
    # @board = Board.find(params[:id])
  end

  def update
    # @board = Board.find(params[:id])
    # clear_params = params.require(:board).permit(:title)
    # clear_params = params[:board].permit(:title)
    # @board = Board.new(clear_params)
    if @board.update(clear_params)
      redirect_to '/',notice: "編輯成功"
    else
      render :edit
    end
  end

  def destroy
    # @board = Board.find(params[:id])
    @board.destroy
    redirect_to root_path ,notice: "刪除成功"
  end

  private
    def find_board
      @board = Board.find(params[:id])
    end
 
    def clear_params
      params.require(:board).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :session_required, only: [:create, :edit, :update]
  before_action :set_board, only: [:new, :create]
  before_action :set_post, only: [:show]
  def new
    @post = Post.new
  end

  def create
    # 普通寫法
    # @post = Post.new(post_params)
    # @post.board = @board
    # @post.user = current_user
    # 以看板角度
    # @post = @board.posts.new(post_params)
    # @post.user = current_user
    # 以使用者角度
    @post = current_user.posts.new(post_params)
    @post.board = @board 


    if @post.save
      redirect_to @board, notice: '新增文章成功'
    else
      render :new
    end
  end

  def show
  end

  def edit
      # @post = Post.find_by(id: params[:id], user: current_user )
      @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: '更新成功'
    else
      render :edit
    end
  end
       
  private
  def set_board
    @board = Board.find(params[:board_id])
  end
  def post_params
    params.require(:post).permit(:title, :content)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :session_required, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(clear_user)
    if @user.save
      redirect_to '/',notice: "註冊成功"
    else
      render :new
    end
  end

  def edit
    
  end
  
  def update
    if current_user.update(clear_user)
      redirect_to edit_users_path, notice: '更新成功'
    else
      
    end
  end
  private
    def clear_user
      params.require(:user).permit(:email, :password ,:password_confirmation, :nickname)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.login(params[:user])
    if user
      session[:user9527] = user.id
      redirect_to root_path, notice: '登入成功'
    else
      redirect_to sign_in_users_path, notice: '登入失敗'
    end
  end

  def destroy
    session[:user9527] = nil
    redirect_to root_path,notice: '已登出'
    
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user9527].present?
      @_user9487 ||= User.find_by(id: session[:user9527])
    else
      nil
    end
  end
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
    <% board.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(board) do |board| %>
  <%= board.label :title , "看板名稱" %>
  <%= board.text_field :title %>
  <%= board.submit '確認' %>
<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>

<%= render 'form' ,board: @board%>

app/views/boards/index.html.erb
<h1>看板標題</h1>
<%= link_to '新增看板', new_board_path %>
<ul>
  <% @boards.each do |board| %>
    <li>
      <%= link_to '修改', edit_board_path(board.id)%>
      <%= link_to "刪除",board ,method: 'delete', data: {confirm: "是否刪除"}%>
      <%= link_to board.title, board %>
    </li>
  <% end %>
</ul>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%= render 'form' ,board: @board%>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>
<%= link_to '新增文章', new_board_post_path(@board) %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%# <%= link_to '修改', edit_board_path(board.id)%> 
      <%# <%= link_to "刪除",board ,method: 'delete', data: {confirm: "是否刪除"} %> 
      <%= link_to post.title, post %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dcard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# link改成pack留著推上線後好找css檔 %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render "shared/navbar" %>
   <%= render "shared/flash" if notice %>
   
    <section class="main_section">
      <%= yield %>
    </section>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編輯文章</h1>
<%= form_for(@post) do |form| %>
  
  <div class="field">
    <%= form.label :title ,'文章標題'%>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content%>
    <%= form.text_area :content%>
  </div>

  <%= form.submit '更新文章' %>

<% end %>

app/views/posts/new.html.erb
<h1>新增文章</h1>
<%= form_for(@post, url: board_posts_path(@board)) do |form| %>
  
  <div class="field">
    <%= form.label :title ,'文章標題'%>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content%>
    <%= form.text_area :content%>
  </div>

  <%= form.submit '新增文章' %>

<% end %>

app/views/posts/show.html.erb
<h2> <%= @post.user.nickname %></h2>
<h1> <%= @post.title %> </h1>


  <%= link_to '編輯', edit_post_path(@post) if @post.owned_by?(current_user) %>

<article>
  <%= simple_format(@post.content) %>
</article>
<%= link_to '回上一頁', :back %>

app/views/shared/_flash.html.erb
<p><%= notice %></p>

app/views/shared/_navbar.html.erb
<nav>
      <ul>
        <li><%= link_to '首頁',root_path %></li>
        <li><%= link_to '看板列表', boards_path%></li>
      </ul>
      <ul>
        <% if current_user %>
          <li><%= current_user.nickname  %></li>
          <li><%= link_to "登出", sign_out_users_path,method: 'delete' %></li>
        <% else %>
          <li><%= link_to '註冊', sign_up_users_path %></li>
          <li><%= link_to '登入', sign_in_users_path %></li>
        <% end %>
      </ul>
    </nav>